verbose: false
instrumentation:
  root: ./src
  excludes: [
    'js/index.js',
    'css/index.js',
    'js/create_store.js',
    'js/router.js',
    'js/history.js'
  ]
  include-all-sources: true
check:
  global:
    branches   : 100
    functions  : 100
    lines      : 100
    statements : 100
